### ISSUE TITLE
numpy dependency has conflicting versions

### ISSUE THREAD

**Issue by qodesign** [Infleqtion/qLDPC#144] opened 2024-11-24 18:47 UTC
I installed qldpc using miniconda with python=3.10 and its own new environment.
There seems to be problems with numpy versions : (test script) 

import networkx as nx
import numpy as np
import qldpc
from qldpc import codes

np.set_printoptions(linewidth=200)

ring_code = codes.RingCode(5)
print(ring_code)
print()
print(ring_code.get_code_params())

when importing this is the error : 

(qldpc) C:\Users\user\Desktop\test>python
Python 3.10.15 | packaged by Anaconda, Inc. | (main, Oct  3 2024, 07:22:19) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import test1

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "C:\Users\user\Desktop\test\test1.py", line 3, in <module>
    import qldpc
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\qldpc\__init__.py", line 3, in <module>
    from . import abstract, codes, decoder, external, objects
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\qldpc\codes\__init__.py", line 1, in <module>
    from .classical import (
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\qldpc\codes\classical.py", line 30, in <module>
    from .common import ClassicalCode
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\qldpc\codes\common.py", line 32, in <module>
    from qldpc import decoder, external
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\qldpc\decoder.py", line 21, in <module>
    import ldpc
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ldpc\__init__.py", line 9, in <module>
    from ldpc.sinter_decoders import SinterBpOsdDecoder
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ldpc\sinter_decoders\__init__.py", line 1, in <module>
    from ldpc.sinter_decoders.sinter_bposd_decoder import SinterBpOsdDecoder
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ldpc\sinter_decoders\sinter_bposd_decoder.py", line 6, in <module>
    from beliefmatching import detector_error_model_to_check_matrices
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\beliefmatching\__init__.py", line 1, in <module>
    from .belief_matching import *
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\beliefmatching\belief_matching.py", line 9, in <module>
    import pymatching
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\pymatching\__init__.py", line 17, in <module>
    from pymatching.matching import Matching  # noqa
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\pymatching\matching.py", line 22, in <module>
    import matplotlib.cbook
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\matplotlib\__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\matplotlib\scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\matplotlib\ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\matplotlib\transforms.py", line 46, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\Desktop\test\test1.py", line 3, in <module>
    import qldpc
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\qldpc\__init__.py", line 3, in <module>
    from . import abstract, codes, decoder, external, objects
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\qldpc\codes\__init__.py", line 1, in <module>
    from .classical import (
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\qldpc\codes\classical.py", line 30, in <module>
    from .common import ClassicalCode
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\qldpc\codes\common.py", line 32, in <module>
    from qldpc import decoder, external
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\qldpc\decoder.py", line 21, in <module>
    import ldpc
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ldpc\__init__.py", line 9, in <module>
    from ldpc.sinter_decoders import SinterBpOsdDecoder
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ldpc\sinter_decoders\__init__.py", line 1, in <module>
    from ldpc.sinter_decoders.sinter_bposd_decoder import SinterBpOsdDecoder
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\ldpc\sinter_decoders\sinter_bposd_decoder.py", line 6, in <module>
    from beliefmatching import detector_error_model_to_check_matrices
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\beliefmatching\__init__.py", line 1, in <module>
    from .belief_matching import *
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\beliefmatching\belief_matching.py", line 9, in <module>
    import pymatching
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\pymatching\__init__.py", line 17, in <module>
    from pymatching.matching import Matching  # noqa
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\pymatching\matching.py", line 22, in <module>
    import matplotlib.cbook
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\matplotlib\__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\matplotlib\scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\matplotlib\ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\matplotlib\transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import
>>> ^Z

(qldpc) C:\Users\user\Desktop\test>

**Comment by perlinm** [comment] 2024-11-24 19:12
Thanks for filing an issue!  The problem is that an updated version of `ldpc` has a conflicting `numpy` dependency.  This should be fixed soon in #141.  I think a temporary fix is to manually install `numpy==1.24.0`.

**Comment by qodesign** [comment] 2024-11-25 01:37
it doesn't look like that fixed it

(qldpc) C:\Users\user\Desktop>pip install --upgrade qldpc
Requirement already satisfied: qldpc in c:\users\user\appdata\roaming\python\python310\site-packages (0.0.18)
Collecting qldpc
  Downloading qldpc-0.0.19-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: cvxpy>=1.3.2 in c:\users\user\appdata\roaming\python\python310\site-packages (from qldpc) (1.6.0)
Requirement already satisfied: diskcache>=5.0.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from qldpc) (5.6.3)
Requirement already satisfied: galois>=0.4.2 in c:\users\user\appdata\roaming\python\python310\site-packages (from qldpc) (0.4.2)
Requirement already satisfied: gurobipy>=10.0.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from qldpc) (12.0.0)
Requirement already satisfied: ldpc==2.1.2 in c:\users\user\appdata\roaming\python\python310\site-packages (from qldpc) (2.1.2)
Requirement already satisfied: networkx>=2.6.2 in c:\users\user\appdata\roaming\python\python310\site-packages (from qldpc) (2.8.6)
Requirement already satisfied: numpy>=1.24.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from qldpc) (2.0.2)
Requirement already satisfied: platformdirs>=4.0.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from qldpc) (4.2.2)
Requirement already satisfied: pymatching>=2.1.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from qldpc) (2.2.0)
Collecting stim>=1.14.0 (from qldpc)
  Downloading stim-1.14.0-cp310-cp310-win_amd64.whl.metadata (4.3 kB)
Requirement already satisfied: sympy>=1.12 in c:\users\user\appdata\roaming\python\python310\site-packages (from qldpc) (1.13.3)
Requirement already satisfied: scipy>=1.9.3 in c:\users\user\appdata\roaming\python\python310\site-packages (from ldpc==2.1.2->qldpc) (1.14.1)
Requirement already satisfied: tqdm in c:\users\user\appdata\roaming\python\python310\site-packages (from ldpc==2.1.2->qldpc) (4.64.0)
Requirement already satisfied: pytest in c:\users\user\appdata\roaming\python\python310\site-packages (from ldpc==2.1.2->qldpc) (8.3.3)
Requirement already satisfied: sinter in c:\users\user\appdata\roaming\python\python310\site-packages (from ldpc==2.1.2->qldpc) (1.11.0)
Requirement already satisfied: BeliefMatching in c:\users\user\appdata\roaming\python\python310\site-packages (from ldpc==2.1.2->qldpc) (0.1.1)
Requirement already satisfied: osqp>=0.6.2 in c:\users\user\appdata\roaming\python\python310\site-packages (from cvxpy>=1.3.2->qldpc) (0.6.7.post3)
Requirement already satisfied: clarabel>=0.5.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from cvxpy>=1.3.2->qldpc) (0.9.0)
Requirement already satisfied: scs>=3.2.4.post1 in c:\users\user\appdata\roaming\python\python310\site-packages (from cvxpy>=1.3.2->qldpc) (3.2.7)
Requirement already satisfied: numba<0.61,>=0.55 in c:\users\user\appdata\roaming\python\python310\site-packages (from galois>=0.4.2->qldpc) (0.60.0)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from galois>=0.4.2->qldpc) (4.3.0)
Requirement already satisfied: matplotlib in c:\users\user\appdata\roaming\python\python310\site-packages (from pymatching>=2.1.0->qldpc) (3.5.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from sympy>=1.12->qldpc) (1.2.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in c:\users\user\appdata\roaming\python\python310\site-packages (from numba<0.61,>=0.55->galois>=0.4.2->qldpc) (0.43.0)
Requirement already satisfied: qdldl in c:\users\user\appdata\roaming\python\python310\site-packages (from osqp>=0.6.2->cvxpy>=1.3.2->qldpc) (0.1.7.post4)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\roaming\python\python310\site-packages (from matplotlib->pymatching>=2.1.0->qldpc) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from matplotlib->pymatching>=2.1.0->qldpc) (4.36.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\appdata\roaming\python\python310\site-packages (from matplotlib->pymatching>=2.1.0->qldpc) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from matplotlib->pymatching>=2.1.0->qldpc) (24.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\user\appdata\roaming\python\python310\site-packages (from matplotlib->pymatching>=2.1.0->qldpc) (9.2.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\user\appdata\roaming\python\python310\site-packages (from matplotlib->pymatching>=2.1.0->qldpc) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\roaming\python\python310\site-packages (from matplotlib->pymatching>=2.1.0->qldpc) (2.8.2)
Requirement already satisfied: iniconfig in c:\users\user\appdata\roaming\python\python310\site-packages (from pytest->ldpc==2.1.2->qldpc) (2.0.0)
Requirement already satisfied: pluggy<2,>=1.5 in c:\users\user\appdata\roaming\python\python310\site-packages (from pytest->ldpc==2.1.2->qldpc) (1.5.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in c:\users\user\appdata\roaming\python\python310\site-packages (from pytest->ldpc==2.1.2->qldpc) (1.2.1)
Requirement already satisfied: tomli>=1 in c:\users\user\appdata\roaming\python\python310\site-packages (from pytest->ldpc==2.1.2->qldpc) (2.0.1)
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python310\site-packages (from pytest->ldpc==2.1.2->qldpc) (0.4.5)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.7->matplotlib->pymatching>=2.1.0->qldpc) (1.16.0)
Downloading qldpc-0.0.19-py3-none-any.whl (89 kB)
Downloading stim-1.14.0-cp310-cp310-win_amd64.whl (2.5 MB)
   ---------------------------------------- 2.5/2.5 MB 11.9 MB/s eta 0:00:00
Installing collected packages: stim, qldpc
  Attempting uninstall: stim
    Found existing installation: stim 1.10.0
    Uninstalling stim-1.10.0:
      Successfully uninstalled stim-1.10.0
  Attempting uninstall: qldpc
    Found existing installation: qLDPC 0.0.18
    Uninstalling qLDPC-0.0.18:
      Successfully uninstalled qLDPC-0.0.18
Successfully installed qldpc-0.0.19 stim-1.14.0

(same error as before when running the test script)

**Comment by perlinm** [comment] 2024-11-25 02:39
Can you try again from a [fresh python environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)?  I suspect what happened is that conda compiled a dependency (possibly `cvxpy`) for one version of `numpy`, and it's not recognizing the need to re-compile it for a different version (or possibly not recognizing the need to install a new version of `numpy`, based on the log that you shared).

The test script you shared works for me if I start with a fresh environment (with python 3.11 or 3.10) and install `qldpc==0.0.19` (the latest version).

**Comment by qodesign** [comment] 2024-11-25 03:00
From a fresh environment and version 0.0.19 the test script runs without a problem. Thanks; you can close this if you like.

**Comment by perlinm** [comment] 2024-11-25 03:32
Great, thanks for testing this!

**Closed** 2024-11-25 03:33 UTC
